require: rubocop-rspec

AllCops:
  Exclude:
    - bin/stubs/*
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - pagopa_soap.gemspec

Metrics/LineLength:
  Exclude:
    - pagopa_soap.gemspec

RSpec/NestedGroups:
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: true
  EnforcedStyle: compact

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/EachWithObject:
  Description: 'Prefer `each_with_object` over `inject` or `reduce`.'
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Description: 'Checks for trailing comma in array literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: no_comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in hash literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: no_comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
  Enabled: true
