require: rubocop-rspec

AllCops:
  Exclude:
    - bin/stubs/*
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - pagopa_soap.gemspec
Metrics/LineLength:
  Exclude:
    - pagopa_soap.gemspec
RSpec/NestedGroups:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/StringLiterals:
  EnforcedStyle: double_quotes
